model:
  target: diffusers.model.ddpm.PLBase
  params:
    model_config:
      prediction_type: epsilon
      pretrained: pretrained/google-ddpm-celebahq-256.ckpt
      unet:
        act_fn: silu
        attention_head_dim: null
        block_out_channels: [128, 128, 256, 256, 512, 512]
        center_input_sample: false
        down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D", "DownBlock2D", "AttnDownBlock2D", "DownBlock2D"]
        downsample_padding: 0
        flip_sin_to_cos: false
        freq_shift: 1
        in_channels: 3
        layers_per_block: 2
        mid_block_scale_factor: 1
        norm_eps: 1e-06
        norm_num_groups: 32
        out_channels: 3
        sample_size: 256
        time_embedding_type: "positional"
        up_block_types: ["UpBlock2D", "AttnUpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"]
    
    sampler_config:
      beta_end: 0.02
      beta_schedule: linear
      beta_start: 0.0001
      clip_sample: true
      num_train_steps: 1000
      trained_betas: null
      variance_type: fixed_small

data:
  predict_batch_size: 4
  num_workers: 0
  val:
    target: diffusers.data.null_image.dataset.NullImageDataset
    params:
      len: 100
  test:
    target: diffusers.data.null_image.dataset.NullImageDataset
    params:
      len: 100
  predict:
    target: diffusers.data.null_image.dataset.NullImageDataset
    params:
      len: 100