model:
  target: diffusers.model.ddpm.PLBase
  params:
    model_config:
      prediction_type: epsilon
      pretrained: pretrained/google-ddpm-celebahq-256.ckpt
      unet:
        act_fn: silu
        attention_head_dim: null
        block_out_channels: [128, 128, 256, 256, 512, 512]
        center_input_sample: false
        down_block_types: ["DownBlock2D", "DownBlock2D", "DownBlock2D", "DownBlock2D", "AttnDownBlock2D", "DownBlock2D"]
        downsample_padding: 0
        flip_sin_to_cos: false
        freq_shift: 1
        in_channels: 3
        layers_per_block: 2
        mid_block_scale_factor: 1
        norm_eps: 1e-06
        norm_num_groups: 32
        out_channels: 3
        sample_size: 256
        time_embedding_type: "positional"
        up_block_types: ["UpBlock2D", "AttnUpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D"]
    
    sampler_config:
      target: diffusers.sampler.sample_ddpm.DDPMSampler
      params:
        num_train_steps: 1000
        num_inference_steps: 20
        beta_start: 0.0001
        beta_end: 0.02
        beta_schedule: linear
        # clip_sample: true
        # trained_betas: null
        # variance_type: fixed_small
      
      target: diffusers.sampler.sample_dpm.DPMSampler
      params:
        # DPM++ 2M
        sampler: dpmpp_2m
        scheduler: karras    # ('', karras)
        solver_type: ''
        discard_next_to_last_sigma: false
        second_order: false
        uses_ensd: false

        # DPM++ SDE 
        sampler: dpmpp_sde
        scheduler: karras    # ('', karras)
        solver_type: ''
        discard_next_to_last_sigma: false
        second_order: true
        uses_ensd: false

        # DPM++ 2M SDE
        sampler: dpmpp_2m_sde
        scheduler: karras    # ('', karras, exponential)
        solver_type: midpoint    # (midpoint, heun)
        discard_next_to_last_sigma: false
        second_order: false
        uses_ensd: false

        # DPM++ 2S
        sampler: dpmpp_2s_ancestral
        scheduler: karras    # ('', karras)
        solver_type: ''
        discard_next_to_last_sigma: false
        second_order: true
        uses_ensd: true

        # DPM++ 3M SDE
        sampler: dpmpp_3m_sde
        scheduler: karras    # ('', karras, exponential)
        solver_type: ''
        discard_next_to_last_sigma: true
        second_order: false
        uses_ensd: false

        # DPM2
        sampler: dpm_2
        scheduler: ''
        solver_type: ''
        discard_next_to_last_sigma: true
        second_order: true
        uses_ensd: false

        # DPM2 karras
        sampler: dpm_2
        scheduler: karras
        solver_type: ''
        discard_next_to_last_sigma: true
        second_order: true
        uses_ensd: true

        # DPM2 a
        sampler: dpm_2_ancestral
        scheduler: ''    # ('', karras)
        solver_type: ''
        discard_next_to_last_sigma: true
        second_order: true
        uses_ensd: true

        # DPM fast
        sampler: dpm_fast
        scheduler: ''
        solver_type: ''
        discard_next_to_last_sigma: false
        second_order: false
        uses_ensd: true

        # DPM adaptive
        sampler: dpm_adaptive
        scheduler: ''
        solver_type: ''
        discard_next_to_last_sigma: false
        second_order: false
        uses_ensd: true

        num_train_steps: 1000
        num_inference_steps: 20
        beta_start: 0.0001
        beta_end: 0.02
        beta_schedule: linear

data:
  predict_batch_size: 4
  num_workers: 0
  val:
    target: diffusers.data.null_image.dataset.NullImageDataset
    params:
      len: 100
  test:
    target: diffusers.data.null_image.dataset.NullImageDataset
    params:
      len: 100
  predict:
    target: diffusers.data.null_image.dataset.NullImageDataset
    params:
      len: 100