model:
  target: diffusers.model.flux.PLBase
  params:
    model_config:
      flow:
        pretrained: 
        in_channels: 64
        vec_in_dim: 768
        context_in_dim: 4096
        hidden_size: 3072
        mlp_ratio: 4.0
        num_heads: 24
        depth: 19
        depth_single_blocks: 38
        axes_dim: [16, 56, 56]
        theta: 10000
        qkv_bias: True
        guidance_embed: False
      ae:
        pretrained:
        resolution: 256
        in_channels: 3
        base_channels: 128
        out_channels: 3
        ch_mult: [1, 2, 4, 4]
        num_res_blocks: 2
        z_channels: 16
        scale_factor: 0.3611
        shift_factor: 0.1159
    
    loss_config: null
    optimizer_config: null

    sampler_config:
      num_steps: 20
      guidance: 3.5