model:
  base_learning_rate: 1.0e-04
  target: diffusers.model.stable_diffusion_stabilityai.StableDiffusion_StabilityAI
  params:
    model_config:
      scale_factor: 0.18215
      prediction_type: 'epsilon'

      unet_config:
        target: diffusers.model.stable_diffusion_stabilityai.UNetModel
        params:
          image_size: 32 # unused
          in_channels: 4
          out_channels: 4
          model_channels: 320
          attention_resolutions: [4, 2, 1]
          num_res_blocks: 2
          channel_mult: [1, 2, 4, 4]
          num_heads: 8
          use_spatial_transformer: True
          transformer_depth: 1
          context_dim: 768
          use_checkpoint: True
          legacy: False
      
      first_stage_config:
        target: diffusers.model.vae.AutoEncoderKL
        params:
          in_channels: 3
          base_channels: 128
          out_channels: 3
          z_channels: 4
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      
      cond_stage_config:
        target: diffusers.model.ldm.modules.encoders.modules.FrozenCLIPEmbedder